{
  "type": "issue",
  "issue": {
    "id": 1814295814,
    "node_id": "I_kwDOABII585sI_UG",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28115",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28115/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28115/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28115/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/28115",
    "number": 28115,
    "state": "open",
    "state_reason": null,
    "title": "Win64 CI failure in feature_versionbits_warning.py",
    "body": "https://cirrus-ci.com/task/6148314429652992?logs=functional_tests#L2861\r\n\r\n```\r\n test  2023-07-19T19:45:37.140000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_framework.py\", line 131, in main\r\n                                       self.run_test()\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\feature_versionbits_warning.py\", line 89, in run_test\r\n                                       self.restart_node(0)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_framework.py\", line 578, in restart_node\r\n                                       self.stop_node(i)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_framework.py\", line 564, in stop_node\r\n                                       self.nodes[i].stop_node(expected_stderr, wait=wait)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_node.py\", line 360, in stop_node\r\n                                       self.wait_until_stopped(expected_stderr=expected_stderr)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_node.py\", line 394, in wait_until_stopped\r\n                                       wait_until_helper(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout, timeout_factor=self.timeout_factor)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\util.py\", line 265, in wait_until_helper\r\n                                       if predicate():\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_node.py\", line 394, in <lambda>\r\n                                       wait_until_helper(lambda: self.is_node_stopped(expected_ret_code=expected_ret_code, **kwargs), timeout=timeout, timeout_factor=self.timeout_factor)\r\n                                     File \"C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\cirrus-ci-build\\test\\functional\\test_framework\\test_node.py\", line 374, in is_node_stopped\r\n                                       assert return_code == expected_ret_code, self._node_msg(\r\n                                   AssertionError: [node 0] Node returned unexpected exit code (3) vs (0) when stopping\r\n test  2023-07-19T19:45:37.140000Z TestFramework (DEBUG): Closing down network thread \r\n test  2023-07-19T19:45:37.202000Z TestFramework (INFO): Stopping nodes \r\n test  2023-07-19T19:45:37.202000Z TestFramework.node0 (DEBUG): Stopping node \r\n```\r\n",
    "user": {
      "login": "jonatack",
      "id": 2415484,
      "node_id": "MDQ6VXNlcjI0MTU0ODQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2415484?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jonatack",
      "html_url": "https://github.com/jonatack",
      "followers_url": "https://api.github.com/users/jonatack/followers",
      "following_url": "https://api.github.com/users/jonatack/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/jonatack/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/jonatack/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/jonatack/subscriptions",
      "organizations_url": "https://api.github.com/users/jonatack/orgs",
      "repos_url": "https://api.github.com/users/jonatack/repos",
      "events_url": "https://api.github.com/users/jonatack/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/jonatack/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 234877,
        "node_id": "MDU6TGFiZWwyMzQ4Nzc=",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
        "name": "Windows",
        "color": "884400",
        "default": false
      },
      {
        "id": 62963516,
        "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
        "name": "Tests",
        "color": "d4c5f9",
        "default": false
      },
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "locked": false,
    "comments": 2,
    "created_at": "2023-07-20T15:39:47Z",
    "updated_at": "2024-01-24T08:18:55Z"
  },
  "events": [
    {
      "event": "commented",
      "id": 1646817279,
      "node_id": "IC_kwDOABII585iKG__",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1646817279",
      "actor": {
        "login": "eval-exec",
        "id": 46400566,
        "node_id": "MDQ6VXNlcjQ2NDAwNTY2",
        "avatar_url": "https://avatars.githubusercontent.com/u/46400566?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eval-exec",
        "html_url": "https://github.com/eval-exec",
        "followers_url": "https://api.github.com/users/eval-exec/followers",
        "following_url": "https://api.github.com/users/eval-exec/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/eval-exec/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/eval-exec/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/eval-exec/subscriptions",
        "organizations_url": "https://api.github.com/users/eval-exec/orgs",
        "repos_url": "https://api.github.com/users/eval-exec/repos",
        "events_url": "https://api.github.com/users/eval-exec/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/eval-exec/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-07-23T11:36:40Z",
      "updated_at": "2023-07-23T11:36:40Z",
      "author_association": "NONE",
      "body": "> `AssertionError: [node 0] Node returned unexpected exit code (3) vs (0) when stopping`\r\n\r\nHello, I think a clue to solve this issue is to find out where the `exit code (3)` is returned? But I didn't find where the `exit code (3)` is returned in the source code.\r\nWhat do you think?",
      "user": {
        "login": "eval-exec",
        "id": 46400566,
        "node_id": "MDQ6VXNlcjQ2NDAwNTY2",
        "avatar_url": "https://avatars.githubusercontent.com/u/46400566?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eval-exec",
        "html_url": "https://github.com/eval-exec",
        "followers_url": "https://api.github.com/users/eval-exec/followers",
        "following_url": "https://api.github.com/users/eval-exec/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/eval-exec/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/eval-exec/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/eval-exec/subscriptions",
        "organizations_url": "https://api.github.com/users/eval-exec/orgs",
        "repos_url": "https://api.github.com/users/eval-exec/repos",
        "events_url": "https://api.github.com/users/eval-exec/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/eval-exec/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/28115#issuecomment-1646817279",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28115"
    },
    {
      "event": "labeled",
      "id": 9896514574,
      "node_id": "LE_lADOABII585sI_UGzwAAAAJN4NQO",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/9896514574",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-07-24T07:20:33Z",
      "label": {
        "name": "Windows",
        "color": "884400"
      }
    },
    {
      "event": "cross-referenced",
      "id": null,
      "node_id": null,
      "url": null,
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-09-25T12:23:49Z",
      "updated_at": "2023-09-25T12:23:49Z",
      "source": {
        "issue": {
          "id": 1911379442,
          "node_id": "I_kwDOABII585x7VXy",
          "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28529",
          "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
          "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28529/labels%7B/name%7D",
          "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28529/comments",
          "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28529/events",
          "html_url": "https://github.com/bitcoin/bitcoin/issues/28529",
          "number": 28529,
          "state": "open",
          "state_reason": null,
          "title": "qa: `PermissionError` in functional tests on Windows",
          "body": "Having an intermittent error in my local Windows:\r\n```\r\n> py -3 test\\functional\\test_runner.py --jobs 40 --timeout-factor=8\r\n...\r\n165/269 - feature_versionbits_warning.py failed, Duration: 59 s\r\n\r\n\r\nstdout:\r\n2023-09-25T11:29:08.904000Z TestFramework (INFO): PRNG seed is: 6135880998339750841\r\n2023-09-25T11:29:09.019000Z TestFramework (INFO): Initializing test directory C:\\Users\\hebasto\\AppData\\Local\\Temp\\test_runner_₿_🏃_20230925_122333\\feature_versionbits_warning_108\r\n2023-09-25T11:29:25.118000Z TestFramework (INFO): Check that there is no warning if previous VB_BLOCKS have <VB_THRESHOLD blocks with unknown versionbits version.\r\n2023-09-25T11:29:43.242000Z TestFramework (INFO): Check that there is a warning if previous VB_BLOCKS have >=VB_THRESHOLD blocks with unknown versionbits version.\r\n2023-09-25T11:29:50.044000Z TestFramework.p2p (WARNING): Connection lost to 127.0.0.1:12296 due to [WinError 10054] An existing connection was forcibly closed by the remote host\r\n2023-09-25T11:30:05.174000Z TestFramework (INFO): Stopping nodes\r\n2023-09-25T11:30:05.548000Z TestFramework (INFO): Cleaning up C:\\Users\\hebasto\\AppData\\Local\\Temp\\test_runner_₿_🏃_20230925_122333\\feature_versionbits_warning_108 on exit\r\n2023-09-25T11:30:05.548000Z TestFramework (INFO): Tests successful\r\n\r\n\r\nstderr:\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\hebasto\\bitcoin/test/functional/feature_versionbits_warning.py\", line 103, in <module>\r\n    VersionBitsWarningTest().main()\r\n  File \"C:\\Users\\hebasto\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 154, in main\r\n    exit_code = self.shutdown()\r\n                ^^^^^^^^^^^^^^^\r\n  File \"C:\\Users\\hebasto\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 361, in shutdown\r\n    shutil.rmtree(self.options.tmpdir)\r\n  File \"C:\\Python311\\Lib\\shutil.py\", line 759, in rmtree\r\n    return _rmtree_unsafe(path, onerror)\r\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\r\nFile \"C:\\Python311\\Lib\\shutil.py\", line 617, in _rmtree_unsafe\r\n    _rmtree_unsafe(fullname, onerror)\r\nFile \"C:\\Python311\\Lib\\shutil.py\", line 617, in _rmtree_unsafe\r\n    _rmtree_unsafe(fullname, onerror)\r\nFile \"C:\\Python311\\Lib\\shutil.py\", line 622, in _rmtree_unsafe\r\n    onerror(os.unlink, fullname, sys.exc_info())\r\nFile \"C:\\Python311\\Lib\\shutil.py\", line 620, in _rmtree_unsafe\r\n    os.unlink(fullname)\r\nPermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\\\Users\\\\hebasto\\\\AppData\\\\Local\\\\Temp\\\\test_runner_₿_🏃_20230925_122333\\\\feature_versionbits_warning_108\\\\node0\\\\regtest\\\\debug.log'\r\n\r\n\r\n166/269 - feature_startupnotify.py passed, Duration: 30 s\r\n...\r\n```",
          "user": {
            "login": "hebasto",
            "id": 32963518,
            "node_id": "MDQ6VXNlcjMyOTYzNTE4",
            "avatar_url": "https://avatars.githubusercontent.com/u/32963518?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hebasto",
            "html_url": "https://github.com/hebasto",
            "followers_url": "https://api.github.com/users/hebasto/followers",
            "following_url": "https://api.github.com/users/hebasto/following%7B/other_user%7D",
            "gists_url": "https://api.github.com/users/hebasto/gists%7B/gist_id%7D",
            "starred_url": "https://api.github.com/users/hebasto/starred%7B/owner%7D%7B/repo%7D",
            "subscriptions_url": "https://api.github.com/users/hebasto/subscriptions",
            "organizations_url": "https://api.github.com/users/hebasto/orgs",
            "repos_url": "https://api.github.com/users/hebasto/repos",
            "events_url": "https://api.github.com/users/hebasto/events%7B/privacy%7D",
            "received_events_url": "https://api.github.com/users/hebasto/received_events",
            "type": "User",
            "site_admin": false
          },
          "labels": [
            {
              "id": 234877,
              "node_id": "MDU6TGFiZWwyMzQ4Nzc=",
              "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
              "name": "Windows",
              "color": "884400",
              "default": false
            },
            {
              "id": 62963516,
              "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
              "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
              "name": "Tests",
              "color": "d4c5f9",
              "default": false
            }
          ],
          "assignees": [],
          "author_association": "MEMBER",
          "locked": false,
          "comments": 3,
          "created_at": "2023-09-25T12:18:39Z",
          "updated_at": "2024-01-08T14:32:36Z"
        },
        "type": "issue"
      }
    },
    {
      "event": "commented",
      "id": 1733619543,
      "node_id": "IC_kwDOABII585nVO9X",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1733619543",
      "actor": {
        "login": "hebasto",
        "id": 32963518,
        "node_id": "MDQ6VXNlcjMyOTYzNTE4",
        "avatar_url": "https://avatars.githubusercontent.com/u/32963518?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hebasto",
        "html_url": "https://github.com/hebasto",
        "followers_url": "https://api.github.com/users/hebasto/followers",
        "following_url": "https://api.github.com/users/hebasto/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hebasto/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hebasto/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hebasto/subscriptions",
        "organizations_url": "https://api.github.com/users/hebasto/orgs",
        "repos_url": "https://api.github.com/users/hebasto/repos",
        "events_url": "https://api.github.com/users/hebasto/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hebasto/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-09-25T12:31:57Z",
      "updated_at": "2023-09-25T12:31:57Z",
      "author_association": "MEMBER",
      "body": "> > `AssertionError: [node 0] Node returned unexpected exit code (3) vs (0) when stopping`\r\n> \r\n> Hello, I think a clue to solve this issue is to find out where the `exit code (3)` is returned? But I didn't find where the `exit code (3)` is returned in the source code. What do you think?\r\n\r\nFrom Microsoft [docs](https://learn.microsoft.com/en-us/previous-versions/k089yyh0(v=vs.140)):\r\n> If the Windows error reporting handler is not invoked, then [`abort`](https://learn.microsoft.com/en-us/previous-versions/k089yyh0(v=vs.140)) calls [`_exit`](https://learn.microsoft.com/en-us/previous-versions/6wdz5232(v=vs.140)) to terminate the process with exit code 3 and returns control to the parent process or the operating system.",
      "user": {
        "login": "hebasto",
        "id": 32963518,
        "node_id": "MDQ6VXNlcjMyOTYzNTE4",
        "avatar_url": "https://avatars.githubusercontent.com/u/32963518?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/hebasto",
        "html_url": "https://github.com/hebasto",
        "followers_url": "https://api.github.com/users/hebasto/followers",
        "following_url": "https://api.github.com/users/hebasto/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/hebasto/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/hebasto/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/hebasto/subscriptions",
        "organizations_url": "https://api.github.com/users/hebasto/orgs",
        "repos_url": "https://api.github.com/users/hebasto/repos",
        "events_url": "https://api.github.com/users/hebasto/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/hebasto/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/28115#issuecomment-1733619543",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28115"
    },
    {
      "event": "labeled",
      "id": 11580838901,
      "node_id": "LE_lADOABII585sI_UGzwAAAAKyRZP1",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/11580838901",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-01-24T08:18:47Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    },
    {
      "event": "labeled",
      "id": 11580840107,
      "node_id": "LE_lADOABII585sI_UGzwAAAAKyRZir",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/11580840107",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-01-24T08:18:55Z",
      "label": {
        "name": "Tests",
        "color": "d4c5f9"
      }
    }
  ]
}