{
  "type": "issue",
  "issue": {
    "id": 1931917044,
    "node_id": "I_kwDOABII585zJrb0",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28613",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28613/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28613/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/28613/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/28613",
    "number": 28613,
    "state": "open",
    "state_reason": null,
    "title": "ERROR: ProcessNewblock: ActivateBestChain failed (Failed to read block)",
    "body": "I have a 13 inch MacBook Pro, M1, 2020, with 16MB RAM, running OS Sonoma 14.0.  A few months ago I had successfully downloaded the entire Bitcoin Core (V25) blockchain and I was updating daily without any issues.  I had my Sparrow wallet connected to Bitcoin Core and the blockchain was reflecting my BTC in my Sparrow wallet.  However, three days ago I received the fatal internal message pop-up message and Bitcoin Core froze completely.  I then deleted/removed Bitcoin Core from my Applications and from the external SDD. \r\n\r\nFor the past two days I have attempted to re-install Bitcoin Core (V25) on an external SDD (Lacie 2TB) after deleting/removing from my Applications and from the external SDD. After all the blocks headers have indexed, the blocks begin to download.  \r\n\r\nYesterday (October 7, 2023) I was accessing the internet via wireless and the download reached block height 222995 before I received the fatal internal message pop-up box: \r\n<img width=\"1099\" alt=\"Screenshot 2023-10-07 at 4 46 18 PM\" src=\"https://github.com/bitcoin/bitcoin/assets/147281390/d9060837-223b-4ed3-9ffe-8aff7b9997e0\">\r\n\r\n<img width=\"1208\" alt=\"Screenshot 2023-10-07 at 4 47 00 PM\" src=\"https://github.com/bitcoin/bitcoin/assets/147281390/1ba2e91e-734b-47b7-9fba-4d60e32ee828\">\r\n\r\nThe debug log from October 7 stated:\r\n<img width=\"644\" alt=\"Screenshot 2023-10-07 at 4 51 44 PM\" src=\"https://github.com/bitcoin/bitcoin/assets/147281390/0c562c21-0ee8-4a1f-ac19-bb4e0f1cf915\">\r\n\r\nToday (October 8, 2024) I was accessing the internet via a wired connection and the download reached block height 196461 before giving the same fatal internal error message pop-up message from yesterday:\r\n<img width=\"739\" alt=\"Screenshot 2023-10-08 at 11 41 10 AM\" src=\"https://github.com/bitcoin/bitcoin/assets/147281390/af143cc9-bd46-49f4-90f7-2eab49d42e36\">\r\n\r\nThe debug log from today stated:\r\n<img width=\"650\" alt=\"Screenshot 2023-10-08 at 11 39 39 AM\" src=\"https://github.com/bitcoin/bitcoin/assets/147281390/be19bc3e-1814-493f-9f75-6155cb0b7ffa\">\r\n\r\nYesterday I ran Apple Diagnostics on my Mac and there are no issues with the internal SDD.  I also believe there are no issues with the external SDD.\r\n\r\nAny guidance on overcoming this issue will be greatly appreciated as I want to make sure I'm running my Sparrow wallet with my Bitcoin Core node.\r\n\r\nThank you, Phil\r\n\r\n\r\n\r\n\r\n",
    "user": {
      "login": "ozziekanga",
      "id": 147281390,
      "node_id": "U_kgDOCMdV7g",
      "avatar_url": "https://avatars.githubusercontent.com/u/147281390?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ozziekanga",
      "html_url": "https://github.com/ozziekanga",
      "followers_url": "https://api.github.com/users/ozziekanga/followers",
      "following_url": "https://api.github.com/users/ozziekanga/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/ozziekanga/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/ozziekanga/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/ozziekanga/subscriptions",
      "organizations_url": "https://api.github.com/users/ozziekanga/orgs",
      "repos_url": "https://api.github.com/users/ozziekanga/repos",
      "events_url": "https://api.github.com/users/ozziekanga/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/ozziekanga/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "NONE",
    "locked": false,
    "comments": 0,
    "created_at": "2023-10-08T16:51:05Z",
    "updated_at": "2023-10-08T16:51:05Z"
  },
  "events": []
}