{
  "type": "issue",
  "issue": {
    "id": 2043346038,
    "node_id": "I_kwDOABII5855yvx2",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29090",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29090/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29090/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29090/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/29090",
    "number": 29090,
    "state": "open",
    "state_reason": null,
    "title": "ci: feature_proxy failing in MSVC job",
    "body": "https://github.com/bitcoin/bitcoin/actions/runs/7219794888/job/19671475361?pr=29088#step:27:73:\r\n```bash\r\n288/288 - feature_proxy.py failed, Duration: 2410 s\r\n\r\nstdout:\r\n2023-12-15T08:53:02.026000Z TestFramework (INFO): PRNG seed is: 197024891591373016\r\n\r\n2023-12-15T08:53:02.026000Z TestFramework (INFO): Initializing test directory D:\\a\\_temp\\test_runner_‚Çø_üèÉ_20231215_084456\\feature_proxy_168\r\n\r\n2023-12-15T09:33:11.259000Z TestFramework (ERROR): Assertion failed\r\n\r\nTraceback (most recent call last):\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 556, in start_nodes\r\n\r\n    node.wait_for_rpc_connection()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 308, in wait_for_rpc_connection\r\n\r\n    self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 182, in _raise_assertion_error\r\n\r\n    raise AssertionError(self._node_msg(msg))\r\n\r\nAssertionError: [node 0] Unable to connect to bitcoind after 2400s\r\n\r\n\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\n\r\n\r\nTraceback (most recent call last):\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 130, in main\r\n\r\n    self.setup()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 297, in setup\r\n\r\n    self.setup_network()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 391, in setup_network\r\n\r\n    self.setup_nodes()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin/test/functional/feature_proxy.py\", line 117, in setup_nodes\r\n\r\n    self.start_nodes()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 559, in start_nodes\r\n\r\n    self.stop_nodes()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 574, in stop_nodes\r\n\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 369, in stop_node\r\n\r\n    self.stop(wait=wait)\r\n\r\n    ^^^^^^^^^\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 199, in __getattr__\r\n\r\n    assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\n\r\nAssertionError: [node 0] Error: no RPC connection\r\n\r\n2023-12-15T09:33:11.314000Z TestFramework (INFO): Stopping nodes\r\n\r\n\r\n\r\nstderr:\r\nTraceback (most recent call last):\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin/test/functional/feature_proxy.py\", line 388, in <module>\r\n\r\n    ProxyTest().main()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 154, in main\r\n\r\n    exit_code = self.shutdown()\r\n\r\n                ^^^^^^^^^^^^^^^\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 313, in shutdown\r\n\r\n    self.stop_nodes()\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 574, in stop_nodes\r\n\r\n    node.stop_node(wait=wait, wait_until_stopped=False)\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 369, in stop_node\r\n\r\n    self.stop(wait=wait)\r\n\r\n    ^^^^^^^^^\r\n\r\n  File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 199, in __getattr__\r\n\r\n    assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\n\r\nAssertionError: [node 0] Error: no RPC connection\r\n\r\n\r\n\r\nCombine the logs and print the last 99999999 lines ...\r\n\r\n============\r\nCombined log for D:\\a\\_temp/test_runner_‚Çø_üèÉ_20231215_084456/feature_proxy_168:\r\n============\r\n\r\n test  2023-12-15T08:53:02.026000Z TestFramework (INFO): PRNG seed is: 197024891591373016 \r\n test  2023-12-15T08:53:02.026000Z TestFramework (DEBUG): Setting up network thread \r\n test  2023-12-15T08:53:02.026000Z TestFramework (INFO): Initializing test directory D:\\a\\_temp\\test_runner_‚Çø_üèÉ_20231215_084456\\feature_proxy_168 \r\n test  2023-12-15T08:53:02.042000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2023-12-15T08:53:02.042000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2023-12-15T08:53:02.042000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2023-12-15T08:53:02.042000Z TestFramework.node3 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2023-12-15T08:53:02.042000Z TestFramework.node4 (DEBUG): bitcoind started, waiting for RPC to come up \r\n test  2023-12-15T09:33:11.259000Z TestFramework.node0 (DEBUG): Stopping node \r\n test  2023-12-15T09:33:11.259000Z TestFramework (ERROR): Assertion failed \r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 556, in start_nodes\r\n                                       node.wait_for_rpc_connection()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 308, in wait_for_rpc_connection\r\n                                       self._raise_assertion_error(\"Unable to connect to bitcoind after {}s\".format(self.rpc_timeout))\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 182, in _raise_assertion_error\r\n                                       raise AssertionError(self._node_msg(msg))\r\n                                   AssertionError: [node 0] Unable to connect to bitcoind after 2400s\r\n                                   During handling of the above exception, another exception occurred:\r\n                                   Traceback (most recent call last):\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 130, in main\r\n                                       self.setup()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 297, in setup\r\n                                       self.setup_network()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 391, in setup_network\r\n                                       self.setup_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin/test/functional/feature_proxy.py\", line 117, in setup_nodes\r\n                                       self.start_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 559, in start_nodes\r\n                                       self.stop_nodes()\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_framework.py\", line 574, in stop_nodes\r\n                                       node.stop_node(wait=wait, wait_until_stopped=False)\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 369, in stop_node\r\n                                       self.stop(wait=wait)\r\n                                       ^^^^^^^^^\r\n                                     File \"D:\\a\\bitcoin\\bitcoin\\test\\functional\\test_framework\\test_node.py\", line 199, in __getattr__\r\n                                       assert self.rpc_connected and self.rpc is not None, self._node_msg(\"Error: no RPC connection\")\r\n                                   AssertionError: [node 0] Error: no RPC connection\r\n test  2023-12-15T09:33:11.259000Z TestFramework (DEBUG): Closing down network thread \r\n test  2023-12-15T09:33:11.314000Z TestFramework (INFO): Stopping nodes \r\n test  2023-12-15T09:33:11.314000Z TestFramework.node0 (DEBUG): Stopping node \r\n```",
    "user": {
      "login": "fanquake",
      "id": 863730,
      "node_id": "MDQ6VXNlcjg2MzczMA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fanquake",
      "html_url": "https://github.com/fanquake",
      "followers_url": "https://api.github.com/users/fanquake/followers",
      "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
      "organizations_url": "https://api.github.com/users/fanquake/orgs",
      "repos_url": "https://api.github.com/users/fanquake/repos",
      "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/fanquake/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 234877,
        "node_id": "MDU6TGFiZWwyMzQ4Nzc=",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
        "name": "Windows",
        "color": "884400",
        "default": false
      },
      {
        "id": 62963516,
        "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
        "name": "Tests",
        "color": "d4c5f9",
        "default": false
      },
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 1,
    "created_at": "2023-12-15T09:57:25Z",
    "updated_at": "2024-01-24T08:17:38Z"
  },
  "events": [
    {
      "event": "cross-referenced",
      "id": null,
      "node_id": null,
      "url": null,
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-12-15T09:58:55Z",
      "updated_at": "2023-12-15T09:58:55Z",
      "source": {
        "issue": {
          "id": 2037423458,
          "node_id": "PR_kwDOABII585hxnwe",
          "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29059",
          "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
          "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29059/labels%7B/name%7D",
          "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29059/comments",
          "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29059/events",
          "html_url": "https://github.com/bitcoin/bitcoin/pull/29059",
          "number": 29059,
          "state": "closed",
          "state_reason": null,
          "title": "Revert \"ci: Only run functional tests on windows in master\"",
          "body": "This PR reverts commit aba4a5887b44bf7cbee9ea0a8e02bb92c1b4147b from https://github.com/bitcoin/bitcoin/pull/28567.\r\n\r\nThe Windows-specific code received [quality](https://github.com/bitcoin/bitcoin/pull/28486) and [performance](https://github.com/bitcoin/bitcoin/pull/29045) improvements recently. So there are no reasons to skip functional tests in PRs anymore.\r\n\r\nIn my own repo, I've run the GHA Windows job more than 100 times with no failure.",
          "user": {
            "login": "hebasto",
            "id": 32963518,
            "node_id": "MDQ6VXNlcjMyOTYzNTE4",
            "avatar_url": "https://avatars.githubusercontent.com/u/32963518?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/hebasto",
            "html_url": "https://github.com/hebasto",
            "followers_url": "https://api.github.com/users/hebasto/followers",
            "following_url": "https://api.github.com/users/hebasto/following%7B/other_user%7D",
            "gists_url": "https://api.github.com/users/hebasto/gists%7B/gist_id%7D",
            "starred_url": "https://api.github.com/users/hebasto/starred%7B/owner%7D%7B/repo%7D",
            "subscriptions_url": "https://api.github.com/users/hebasto/subscriptions",
            "organizations_url": "https://api.github.com/users/hebasto/orgs",
            "repos_url": "https://api.github.com/users/hebasto/repos",
            "events_url": "https://api.github.com/users/hebasto/events%7B/privacy%7D",
            "received_events_url": "https://api.github.com/users/hebasto/received_events",
            "type": "User",
            "site_admin": false
          },
          "labels": [
            {
              "id": 234877,
              "node_id": "MDU6TGFiZWwyMzQ4Nzc=",
              "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Windows",
              "name": "Windows",
              "color": "884400",
              "default": false
            },
            {
              "id": 62963516,
              "node_id": "MDU6TGFiZWw2Mjk2MzUxNg==",
              "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/Tests",
              "name": "Tests",
              "color": "d4c5f9",
              "default": false
            }
          ],
          "assignees": [],
          "author_association": "MEMBER",
          "locked": false,
          "comments": 5,
          "pull_request": {
            "url": "https://api.github.com/repos/bitcoin/bitcoin/pulls/29059",
            "html_url": "https://github.com/bitcoin/bitcoin/pull/29059",
            "diff_url": "https://github.com/bitcoin/bitcoin/pull/29059.diff",
            "patch_url": "https://github.com/bitcoin/bitcoin/pull/29059.patch"
          },
          "closed_at": "2023-12-12T13:43:28Z",
          "created_at": "2023-12-12T10:14:17Z",
          "updated_at": "2023-12-15T10:11:53Z"
        },
        "type": "issue"
      }
    },
    {
      "event": "commented",
      "id": 1860741967,
      "node_id": "IC_kwDOABII585u6KtP",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/comments/1860741967",
      "actor": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-12-18T15:03:45Z",
      "updated_at": "2023-12-18T15:03:45Z",
      "author_association": "MEMBER",
      "body": "Similar failure, different test: https://github.com/bitcoin/bitcoin/actions/runs/7249043694/job/19746211856#step:27:521.",
      "user": {
        "login": "fanquake",
        "id": 863730,
        "node_id": "MDQ6VXNlcjg2MzczMA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/863730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/fanquake",
        "html_url": "https://github.com/fanquake",
        "followers_url": "https://api.github.com/users/fanquake/followers",
        "following_url": "https://api.github.com/users/fanquake/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/fanquake/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/fanquake/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/fanquake/subscriptions",
        "organizations_url": "https://api.github.com/users/fanquake/orgs",
        "repos_url": "https://api.github.com/users/fanquake/repos",
        "events_url": "https://api.github.com/users/fanquake/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/fanquake/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/bitcoin/bitcoin/issues/29090#issuecomment-1860741967",
      "issue_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29090"
    },
    {
      "event": "labeled",
      "id": 11278529276,
      "node_id": "LE_lADOABII5855yvx2zwAAAAKgQLL8",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/11278529276",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-12-18T15:43:47Z",
      "label": {
        "name": "Windows",
        "color": "884400"
      }
    },
    {
      "event": "labeled",
      "id": 11278529286,
      "node_id": "LE_lADOABII5855yvx2zwAAAAKgQLMG",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/11278529286",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2023-12-18T15:43:47Z",
      "label": {
        "name": "Tests",
        "color": "d4c5f9"
      }
    },
    {
      "event": "labeled",
      "id": 11580825687,
      "node_id": "LE_lADOABII5855yvx2zwAAAAKyRWBX",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/11580825687",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-01-24T08:17:38Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    }
  ]
}