{
  "type": "issue",
  "issue": {
    "id": 2167444541,
    "node_id": "I_kwDOABII586BMJQ9",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29556",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29556/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29556/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/29556/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/29556",
    "number": 29556,
    "state": "open",
    "state_reason": null,
    "title": "Exception: St11logic_error - Not all cached coins were erased - bitcoin in Runaway exception",
    "body": "### Is there an existing issue for this?\r\n\r\n- [X] I have searched the existing issues\r\n\r\n### Current behaviour\r\n\r\nI have merged the Bitcoin PoW/PoT code into the BTC 26x baseline. After 8 hours of running I generally see the error:\r\n***********************\r\nException: St11logic_error\r\nNot all cached coins were erased\r\nbitcoin in Runaway exception\r\n\r\nThe code was posted here:\r\nhttps://github.com/bitcoin/bitcoin/pull/29455/\r\n\r\nNot sure why the title was deleted...\r\n\r\nBitcoinPoW (BTCW) is a modified version of Bitcoin. It uses proof of transactions as a way to perform work. This means that each wallet on the BTCW network generally has between 20,000 and 100,000 utxos and the txids of those utxos are used in the hashing.\r\n\r\nThe exception points to the Pool code here: https://github.com/bitcoin/bitcoin/blob/26.x/src/support/allocators/pool.h\r\n\r\nI have not debugged in detail the issue, but seems that there is a possible bug in the pool.h code that hasn't surfaced because of low utxo counts in BTC wallets.\r\n\r\nIt should also be noted that:\r\n\r\nusing CCoinsMap = std::unordered_map<COutPoint,\r\n                                     CCoinsCacheEntry,\r\n                                     SaltedOutpointHasher,\r\n                                     std::equal_to<COutPoint>,\r\n                                     PoolAllocator<std::pair<const COutPoint, CCoinsCacheEntry>,\r\n                                                   sizeof(std::pair<const COutPoint, CCoinsCacheEntry>) + sizeof(void*) * 4>>;\r\n\r\nIs new as of 26.x. Previous version of BTCW was using 21.x baseline and never encountered this issue. 25.x and earlier baselines never used the PoolAllocator for the CCoinsMap.\r\n\r\nTurns out that if I comment out all the custom Pool Alloc/Dealloc code and only use new/delete as shown below, the problem goes away. This points to the below possibllities. \r\n\r\nA) multi threading issues within these methods. - new/delete is thread safe, but the custom code is not.\r\nB) byte alignment issues, using 4 different variations of paths: \r\n-Allocate/Deallocate \r\n-Allocate/delete\r\n-new/Deallocate\r\n-new/delete -> this is safe and the issue is not present.\r\n\r\nHave there been test cases to cover the 4 paths above?\r\n\r\n/// NOTE: This code fixes the issue.\r\n    void* Allocate(std::size_t bytes, std::size_t alignment)\r\n    {\r\n        // Can't use the pool => use operator new()\r\n        return ::operator new (bytes, std::align_val_t{alignment});\r\n    }\r\n\r\n    void Deallocate(void* p, std::size_t bytes, std::size_t alignment) noexcept\r\n    {\r\n            // Can't use the pool => forward deallocation to ::operator delete().\r\n            ::operator delete (p, std::align_val_t{alignment});\r\n    }\r\n\r\n### Expected behaviour\r\n\r\nException should not be thrown.\r\n\r\n### Steps to reproduce\r\n\r\nModify the 26.x baseline with BTCW code here:\r\nhttps://github.com/bitcoin/bitcoin/pull/29455/\r\n\r\nand mine on the BTCW network with 50,000 utxos.\r\n\r\n### Relevant log output\r\n\r\n***********************\r\nException: Stlllogic_error\r\nNot all cached coins were erased\r\nbitcoin in Runaway exception\r\n\r\n### How did you obtain Bitcoin Core\r\n\r\nCompiled from source\r\n\r\n### What version of Bitcoin Core are you using?\r\n\r\nhttps://github.com/bitcoin/bitcoin/commit/74df372750ceb4ccdfe310e18f14cdd3abac4a51\r\n\r\n### Operating system and version\r\n\r\nUbuntu 20 and 22\r\n\r\n### Machine specifications\r\n\r\n_No response_",
    "user": {
      "login": "bitcoin-pow",
      "id": 153294189,
      "node_id": "U_kgDOCSMVbQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/153294189?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bitcoin-pow",
      "html_url": "https://github.com/bitcoin-pow",
      "followers_url": "https://api.github.com/users/bitcoin-pow/followers",
      "following_url": "https://api.github.com/users/bitcoin-pow/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/bitcoin-pow/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/bitcoin-pow/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/bitcoin-pow/subscriptions",
      "organizations_url": "https://api.github.com/users/bitcoin-pow/orgs",
      "repos_url": "https://api.github.com/users/bitcoin-pow/repos",
      "events_url": "https://api.github.com/users/bitcoin-pow/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/bitcoin-pow/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [],
    "assignees": [],
    "author_association": "NONE",
    "locked": false,
    "comments": 0,
    "created_at": "2024-03-04T18:11:38Z",
    "updated_at": "2024-03-04T18:38:59Z"
  },
  "events": [
    {
      "event": "renamed",
      "id": 12003246140,
      "node_id": "RTE_lADOABII586BMJQ9zwAAAALLcwA8",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/12003246140",
      "actor": {
        "login": "bitcoin-pow",
        "id": 153294189,
        "node_id": "U_kgDOCSMVbQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/153294189?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/bitcoin-pow",
        "html_url": "https://github.com/bitcoin-pow",
        "followers_url": "https://api.github.com/users/bitcoin-pow/followers",
        "following_url": "https://api.github.com/users/bitcoin-pow/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/bitcoin-pow/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/bitcoin-pow/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/bitcoin-pow/subscriptions",
        "organizations_url": "https://api.github.com/users/bitcoin-pow/orgs",
        "repos_url": "https://api.github.com/users/bitcoin-pow/repos",
        "events_url": "https://api.github.com/users/bitcoin-pow/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/bitcoin-pow/received_events",
        "type": "User",
        "site_admin": false
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2024-03-04T18:38:44Z",
      "rename": {
        "from": "Exception: Stlllogic_error - Not all cached coins were erased - bitcoin in Runaway exception",
        "to": "Exception: St11logic_error - Not all cached coins were erased - bitcoin in Runaway exception"
      }
    }
  ]
}